# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\temp\indicatrix_mapper_dialog_base_new.ui'
#
# Created: Thu Nov 26 19:14:41 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Tiss(object):
    def setupUi(self, Tiss):
        Tiss.setObjectName(_fromUtf8("Tiss"))
        Tiss.resize(630, 288)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tiss.sizePolicy().hasHeightForWidth())
        Tiss.setSizePolicy(sizePolicy)
        Tiss.setMinimumSize(QtCore.QSize(500, 280))
        Tiss.setMaximumSize(QtCore.QSize(1000, 500))
        self.btnRun = QtGui.QPushButton(Tiss)
        self.btnRun.setGeometry(QtCore.QRect(470, 260, 131, 23))
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.lblLongMin_2 = QtGui.QLabel(Tiss)
        self.lblLongMin_2.setGeometry(QtCore.QRect(200, 80, 50, 20))
        self.lblLongMin_2.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_2.setObjectName(_fromUtf8("lblLongMin_2"))
        self.lblLongMin_3 = QtGui.QLabel(Tiss)
        self.lblLongMin_3.setGeometry(QtCore.QRect(100, 120, 50, 20))
        self.lblLongMin_3.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_3.setObjectName(_fromUtf8("lblLongMin_3"))
        self.lblLongMin_4 = QtGui.QLabel(Tiss)
        self.lblLongMin_4.setGeometry(QtCore.QRect(100, 40, 50, 20))
        self.lblLongMin_4.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_4.setObjectName(_fromUtf8("lblLongMin_4"))
        self.lblLongMin_5 = QtGui.QLabel(Tiss)
        self.lblLongMin_5.setGeometry(QtCore.QRect(0, 220, 50, 20))
        self.lblLongMin_5.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_5.setObjectName(_fromUtf8("lblLongMin_5"))
        self.spbLatMin_2 = QtGui.QSpinBox(Tiss)
        self.spbLatMin_2.setGeometry(QtCore.QRect(100, 240, 50, 20))
        self.spbLatMin_2.setMinimum(-90)
        self.spbLatMin_2.setMaximum(90)
        self.spbLatMin_2.setProperty("value", -90)
        self.spbLatMin_2.setObjectName(_fromUtf8("spbLatMin_2"))
        self.spbLongMin_2 = QtGui.QSpinBox(Tiss)
        self.spbLongMin_2.setGeometry(QtCore.QRect(50, 220, 50, 20))
        self.spbLongMin_2.setMinimum(-180)
        self.spbLongMin_2.setMaximum(180)
        self.spbLongMin_2.setProperty("value", -150)
        self.spbLongMin_2.setObjectName(_fromUtf8("spbLongMin_2"))
        self.spbLongMax_2 = QtGui.QSpinBox(Tiss)
        self.spbLongMax_2.setGeometry(QtCore.QRect(150, 220, 50, 20))
        self.spbLongMax_2.setMinimum(-180)
        self.spbLongMax_2.setMaximum(180)
        self.spbLongMax_2.setProperty("value", 150)
        self.spbLongMax_2.setObjectName(_fromUtf8("spbLongMax_2"))
        self.lblLongMin_6 = QtGui.QLabel(Tiss)
        self.lblLongMin_6.setGeometry(QtCore.QRect(100, 260, 50, 20))
        self.lblLongMin_6.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_6.setObjectName(_fromUtf8("lblLongMin_6"))
        self.lblLongMin_7 = QtGui.QLabel(Tiss)
        self.lblLongMin_7.setGeometry(QtCore.QRect(200, 220, 50, 20))
        self.lblLongMin_7.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_7.setObjectName(_fromUtf8("lblLongMin_7"))
        self.lblLongMin_8 = QtGui.QLabel(Tiss)
        self.lblLongMin_8.setGeometry(QtCore.QRect(100, 180, 50, 20))
        self.lblLongMin_8.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin_8.setObjectName(_fromUtf8("lblLongMin_8"))
        self.spbLatMax_2 = QtGui.QSpinBox(Tiss)
        self.spbLatMax_2.setGeometry(QtCore.QRect(100, 200, 50, 20))
        self.spbLatMax_2.setMinimum(-90)
        self.spbLatMax_2.setMaximum(90)
        self.spbLatMax_2.setProperty("value", 90)
        self.spbLatMax_2.setObjectName(_fromUtf8("spbLatMax_2"))
        self.label_13 = QtGui.QLabel(Tiss)
        self.label_13.setGeometry(QtCore.QRect(50, 150, 150, 20))
        self.label_13.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Tiss)
        self.label_14.setGeometry(QtCore.QRect(50, 10, 150, 20))
        self.label_14.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_7 = QtGui.QLabel(Tiss)
        self.label_7.setGeometry(QtCore.QRect(280, 230, 110, 20))
        self.label_7.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lblRadius_2 = QtGui.QLabel(Tiss)
        self.lblRadius_2.setGeometry(QtCore.QRect(280, 190, 110, 20))
        self.lblRadius_2.setMinimumSize(QtCore.QSize(80, 20))
        self.lblRadius_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRadius_2.setObjectName(_fromUtf8("lblRadius_2"))
        self.spbLatRes_2 = QtGui.QSpinBox(Tiss)
        self.spbLatRes_2.setGeometry(QtCore.QRect(320, 210, 40, 20))
        self.spbLatRes_2.setMaximum(90)
        self.spbLatRes_2.setProperty("value", 30)
        self.spbLatRes_2.setObjectName(_fromUtf8("spbLatRes_2"))
        self.spbLongRes_2 = QtGui.QSpinBox(Tiss)
        self.spbLongRes_2.setGeometry(QtCore.QRect(320, 250, 40, 20))
        self.spbLongRes_2.setMaximum(90)
        self.spbLongRes_2.setProperty("value", 30)
        self.spbLongRes_2.setObjectName(_fromUtf8("spbLongRes_2"))
        self.lblCircleSeg_3 = QtGui.QLabel(Tiss)
        self.lblCircleSeg_3.setGeometry(QtCore.QRect(430, 20, 100, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCircleSeg_3.sizePolicy().hasHeightForWidth())
        self.lblCircleSeg_3.setSizePolicy(sizePolicy)
        self.lblCircleSeg_3.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCircleSeg_3.setFont(font)
        self.lblCircleSeg_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCircleSeg_3.setObjectName(_fromUtf8("lblCircleSeg_3"))
        self.spbLongMin = QtGui.QSpinBox(Tiss)
        self.spbLongMin.setGeometry(QtCore.QRect(50, 80, 50, 20))
        self.spbLongMin.setMinimum(-180)
        self.spbLongMin.setMaximum(180)
        self.spbLongMin.setProperty("value", -150)
        self.spbLongMin.setObjectName(_fromUtf8("spbLongMin"))
        self.spbLongMax = QtGui.QSpinBox(Tiss)
        self.spbLongMax.setGeometry(QtCore.QRect(150, 80, 50, 20))
        self.spbLongMax.setMinimum(-180)
        self.spbLongMax.setMaximum(180)
        self.spbLongMax.setProperty("value", 150)
        self.spbLongMax.setObjectName(_fromUtf8("spbLongMax"))
        self.spbLatMax = QtGui.QSpinBox(Tiss)
        self.spbLatMax.setGeometry(QtCore.QRect(100, 60, 50, 20))
        self.spbLatMax.setMinimum(-89)
        self.spbLatMax.setMaximum(89)
        self.spbLatMax.setProperty("value", 60)
        self.spbLatMax.setObjectName(_fromUtf8("spbLatMax"))
        self.lblLongMin = QtGui.QLabel(Tiss)
        self.lblLongMin.setGeometry(QtCore.QRect(0, 80, 50, 20))
        self.lblLongMin.setMinimumSize(QtCore.QSize(50, 20))
        self.lblLongMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin.setObjectName(_fromUtf8("lblLongMin"))
        self.spbLatMin = QtGui.QSpinBox(Tiss)
        self.spbLatMin.setGeometry(QtCore.QRect(100, 100, 50, 20))
        self.spbLatMin.setMinimum(-89)
        self.spbLatMin.setMaximum(89)
        self.spbLatMin.setProperty("value", -60)
        self.spbLatMin.setObjectName(_fromUtf8("spbLatMin"))
        self.spbLineSeg = QtGui.QSpinBox(Tiss)
        self.spbLineSeg.setGeometry(QtCore.QRect(540, 80, 50, 20))
        self.spbLineSeg.setMinimum(5)
        self.spbLineSeg.setMaximum(200)
        self.spbLineSeg.setProperty("value", 100)
        self.spbLineSeg.setObjectName(_fromUtf8("spbLineSeg"))
        self.label_10 = QtGui.QLabel(Tiss)
        self.label_10.setGeometry(QtCore.QRect(290, 10, 100, 20))
        self.label_10.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lblRadius = QtGui.QLabel(Tiss)
        self.lblRadius.setGeometry(QtCore.QRect(280, 50, 110, 20))
        self.lblRadius.setMinimumSize(QtCore.QSize(80, 20))
        self.lblRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRadius.setObjectName(_fromUtf8("lblRadius"))
        self.label_6 = QtGui.QLabel(Tiss)
        self.label_6.setGeometry(QtCore.QRect(280, 90, 110, 20))
        self.label_6.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.spbLatRes = QtGui.QSpinBox(Tiss)
        self.spbLatRes.setGeometry(QtCore.QRect(320, 70, 40, 20))
        self.spbLatRes.setMaximum(90)
        self.spbLatRes.setProperty("value", 30)
        self.spbLatRes.setObjectName(_fromUtf8("spbLatRes"))
        self.spbLongRes = QtGui.QSpinBox(Tiss)
        self.spbLongRes.setGeometry(QtCore.QRect(320, 110, 40, 20))
        self.spbLongRes.setMaximum(90)
        self.spbLongRes.setProperty("value", 30)
        self.spbLongRes.setObjectName(_fromUtf8("spbLongRes"))
        self.lblCircleSeg_2 = QtGui.QLabel(Tiss)
        self.lblCircleSeg_2.setGeometry(QtCore.QRect(430, 80, 100, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCircleSeg_2.sizePolicy().hasHeightForWidth())
        self.lblCircleSeg_2.setSizePolicy(sizePolicy)
        self.lblCircleSeg_2.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCircleSeg_2.setFont(font)
        self.lblCircleSeg_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCircleSeg_2.setObjectName(_fromUtf8("lblCircleSeg_2"))
        self.label_11 = QtGui.QLabel(Tiss)
        self.label_11.setGeometry(QtCore.QRect(444, 231, 50, 20))
        self.label_11.setMinimumSize(QtCore.QSize(50, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.spbRadiusKm = QtGui.QDoubleSpinBox(Tiss)
        self.spbRadiusKm.setGeometry(QtCore.QRect(504, 231, 70, 20))
        self.spbRadiusKm.setDecimals(3)
        self.spbRadiusKm.setMinimum(1.0)
        self.spbRadiusKm.setMaximum(5000.0)
        self.spbRadiusKm.setProperty("value", 667.17)
        self.spbRadiusKm.setObjectName(_fromUtf8("spbRadiusKm"))
        self.label_9 = QtGui.QLabel(Tiss)
        self.label_9.setGeometry(QtCore.QRect(450, 200, 50, 20))
        self.label_9.setMinimumSize(QtCore.QSize(50, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.spbRadiusDg = QtGui.QDoubleSpinBox(Tiss)
        self.spbRadiusDg.setGeometry(QtCore.QRect(504, 201, 70, 20))
        self.spbRadiusDg.setDecimals(3)
        self.spbRadiusDg.setMinimum(1.0)
        self.spbRadiusDg.setMaximum(5000.0)
        self.spbRadiusDg.setProperty("value", 6.0)
        self.spbRadiusDg.setObjectName(_fromUtf8("spbRadiusDg"))
        self.label_8 = QtGui.QLabel(Tiss)
        self.label_8.setGeometry(QtCore.QRect(450, 170, 130, 20))
        self.label_8.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_12 = QtGui.QLabel(Tiss)
        self.label_12.setGeometry(QtCore.QRect(410, 50, 120, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.spbRadius = QtGui.QSpinBox(Tiss)
        self.spbRadius.setGeometry(QtCore.QRect(540, 50, 67, 20))
        self.spbRadius.setMinimum(6000000)
        self.spbRadius.setMaximum(7000000)
        self.spbRadius.setSingleStep(0)
        self.spbRadius.setProperty("value", 6371000)
        self.spbRadius.setObjectName(_fromUtf8("spbRadius"))
        self.chkBoxSPole = QtGui.QCheckBox(Tiss)
        self.chkBoxSPole.setGeometry(QtCore.QRect(460, 150, 130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkBoxSPole.setFont(font)
        self.chkBoxSPole.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBoxSPole.setObjectName(_fromUtf8("chkBoxSPole"))
        self.spbCircleSeg = QtGui.QSpinBox(Tiss)
        self.spbCircleSeg.setGeometry(QtCore.QRect(540, 20, 40, 20))
        self.spbCircleSeg.setMinimum(5)
        self.spbCircleSeg.setMaximum(100)
        self.spbCircleSeg.setProperty("value", 50)
        self.spbCircleSeg.setObjectName(_fromUtf8("spbCircleSeg"))
        self.chkBoxNPole = QtGui.QCheckBox(Tiss)
        self.chkBoxNPole.setGeometry(QtCore.QRect(460, 130, 130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkBoxNPole.setFont(font)
        self.chkBoxNPole.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBoxNPole.setObjectName(_fromUtf8("chkBoxNPole"))
        self.chkBoxAux = QtGui.QCheckBox(Tiss)
        self.chkBoxAux.setGeometry(QtCore.QRect(460, 110, 130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkBoxAux.setFont(font)
        self.chkBoxAux.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBoxAux.setObjectName(_fromUtf8("chkBoxAux"))

        self.retranslateUi(Tiss)
        QtCore.QMetaObject.connectSlotsByName(Tiss)

    def retranslateUi(self, Tiss):
        Tiss.setWindowTitle(_translate("Tiss", "Tiss", None))
        self.btnRun.setText(_translate("Tiss", "Run!", None))
        self.lblLongMin_2.setText(_translate("Tiss", "Lon. max", None))
        self.lblLongMin_3.setText(_translate("Tiss", "Lat. min", None))
        self.lblLongMin_4.setText(_translate("Tiss", "Lat. max", None))
        self.lblLongMin_5.setText(_translate("Tiss", "Lon. min", None))
        self.lblLongMin_6.setText(_translate("Tiss", "Lat. min", None))
        self.lblLongMin_7.setText(_translate("Tiss", "Lon. max", None))
        self.lblLongMin_8.setText(_translate("Tiss", "Lat. max", None))
        self.label_13.setText(_translate("Tiss", "Graticule", None))
        self.label_14.setText(_translate("Tiss", "Tisses", None))
        self.label_7.setText(_translate("Tiss", "Longitude resolution:", None))
        self.lblRadius_2.setText(_translate("Tiss", "Latitude resolution: ", None))
        self.lblCircleSeg_3.setText(_translate("Tiss", "Tiss segments", None))
        self.lblLongMin.setText(_translate("Tiss", "Lon. min", None))
        self.label_10.setText(_translate("Tiss", "Extent", None))
        self.lblRadius.setText(_translate("Tiss", "Latitude resolution: ", None))
        self.label_6.setText(_translate("Tiss", "Longitude resolution:", None))
        self.lblCircleSeg_2.setText(_translate("Tiss", "Line segments", None))
        self.label_11.setText(_translate("Tiss", "[km]: ", None))
        self.label_9.setText(_translate("Tiss", "[degree]: ", None))
        self.label_8.setText(_translate("Tiss", "Radius of the circles", None))
        self.label_12.setText(_translate("Tiss", "Spherical radius [m]", None))
        self.chkBoxSPole.setText(_translate("Tiss", "Circle on south pole", None))
        self.chkBoxNPole.setText(_translate("Tiss", "Circle on north pole", None))
        self.chkBoxAux.setText(_translate("Tiss", "Auxiliary points", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Tiss = QtGui.QDialog()
    ui = Ui_Tiss()
    ui.setupUi(Tiss)
    Tiss.show()
    sys.exit(app.exec_())

