# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\git\tiss\indicatrix_mapper_dialog_base.ui'
#
# Created: Sat May 02 15:38:32 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Tiss(object):
    def setupUi(self, Tiss):
        Tiss.setObjectName(_fromUtf8("Tiss"))
        Tiss.resize(825, 280)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tiss.sizePolicy().hasHeightForWidth())
        Tiss.setSizePolicy(sizePolicy)
        Tiss.setMinimumSize(QtCore.QSize(750, 280))
        Tiss.setMaximumSize(QtCore.QSize(1000, 500))
        self.btnRun = QtGui.QPushButton(Tiss)
        self.btnRun.setGeometry(QtCore.QRect(310, 250, 131, 23))
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.layoutWidget = QtGui.QWidget(Tiss)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 775, 227))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spbLongMin = QtGui.QSpinBox(self.layoutWidget)
        self.spbLongMin.setMinimum(-180)
        self.spbLongMin.setMaximum(180)
        self.spbLongMin.setProperty("value", -150)
        self.spbLongMin.setObjectName(_fromUtf8("spbLongMin"))
        self.gridLayout.addWidget(self.spbLongMin, 4, 1, 1, 1)
        self.lblLongMax = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLongMax.sizePolicy().hasHeightForWidth())
        self.lblLongMax.setSizePolicy(sizePolicy)
        self.lblLongMax.setMinimumSize(QtCore.QSize(72, 27))
        self.lblLongMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMax.setObjectName(_fromUtf8("lblLongMax"))
        self.gridLayout.addWidget(self.lblLongMax, 4, 4, 1, 1)
        self.spbLatMax = QtGui.QSpinBox(self.layoutWidget)
        self.spbLatMax.setMinimum(-89)
        self.spbLatMax.setMaximum(89)
        self.spbLatMax.setProperty("value", 60)
        self.spbLatMax.setObjectName(_fromUtf8("spbLatMax"))
        self.gridLayout.addWidget(self.spbLatMax, 3, 2, 1, 1)
        self.lblLongMin = QtGui.QLabel(self.layoutWidget)
        self.lblLongMin.setMinimumSize(QtCore.QSize(65, 27))
        self.lblLongMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLongMin.setObjectName(_fromUtf8("lblLongMin"))
        self.gridLayout.addWidget(self.lblLongMin, 4, 0, 1, 1)
        self.lblLatMax = QtGui.QLabel(self.layoutWidget)
        self.lblLatMax.setMinimumSize(QtCore.QSize(66, 27))
        self.lblLatMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLatMax.setObjectName(_fromUtf8("lblLatMax"))
        self.gridLayout.addWidget(self.lblLatMax, 2, 2, 1, 1)
        self.spbLatMin = QtGui.QSpinBox(self.layoutWidget)
        self.spbLatMin.setMinimum(-89)
        self.spbLatMin.setMaximum(89)
        self.spbLatMin.setProperty("value", -60)
        self.spbLatMin.setObjectName(_fromUtf8("spbLatMin"))
        self.gridLayout.addWidget(self.spbLatMin, 5, 2, 1, 1)
        self.spbLongMax = QtGui.QSpinBox(self.layoutWidget)
        self.spbLongMax.setMinimum(-180)
        self.spbLongMax.setMaximum(180)
        self.spbLongMax.setProperty("value", 150)
        self.spbLongMax.setObjectName(_fromUtf8("spbLongMax"))
        self.gridLayout.addWidget(self.spbLongMax, 4, 3, 1, 1)
        self.spbLineSeg = QtGui.QSpinBox(self.layoutWidget)
        self.spbLineSeg.setMinimum(5)
        self.spbLineSeg.setMaximum(100)
        self.spbLineSeg.setProperty("value", 50)
        self.spbLineSeg.setObjectName(_fromUtf8("spbLineSeg"))
        self.gridLayout.addWidget(self.spbLineSeg, 2, 9, 1, 1)
        self.lblLatMin = QtGui.QLabel(self.layoutWidget)
        self.lblLatMin.setMinimumSize(QtCore.QSize(66, 27))
        self.lblLatMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLatMin.setObjectName(_fromUtf8("lblLatMin"))
        self.gridLayout.addWidget(self.lblLatMin, 6, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(66, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 5)
        self.lblRadius = QtGui.QLabel(self.layoutWidget)
        self.lblRadius.setMinimumSize(QtCore.QSize(135, 27))
        self.lblRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRadius.setObjectName(_fromUtf8("lblRadius"))
        self.gridLayout.addWidget(self.lblRadius, 1, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(144, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 2)
        self.spbLatRes = QtGui.QSpinBox(self.layoutWidget)
        self.spbLatRes.setMaximum(90)
        self.spbLatRes.setProperty("value", 30)
        self.spbLatRes.setObjectName(_fromUtf8("spbLatRes"))
        self.gridLayout.addWidget(self.spbLatRes, 1, 2, 1, 1)
        self.spbLongRes = QtGui.QSpinBox(self.layoutWidget)
        self.spbLongRes.setMaximum(90)
        self.spbLongRes.setProperty("value", 30)
        self.spbLongRes.setObjectName(_fromUtf8("spbLongRes"))
        self.gridLayout.addWidget(self.spbLongRes, 1, 5, 1, 1)
        self.lblCircleSeg_2 = QtGui.QLabel(self.layoutWidget)
        self.lblCircleSeg_2.setMinimumSize(QtCore.QSize(144, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCircleSeg_2.setFont(font)
        self.lblCircleSeg_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCircleSeg_2.setObjectName(_fromUtf8("lblCircleSeg_2"))
        self.gridLayout.addWidget(self.lblCircleSeg_2, 2, 6, 1, 3)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(66, 27))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 6, 1, 1)
        self.spbRadiusKm = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spbRadiusKm.setDecimals(3)
        self.spbRadiusKm.setMinimum(1.0)
        self.spbRadiusKm.setMaximum(5000.0)
        self.spbRadiusKm.setProperty("value", 800.0)
        self.spbRadiusKm.setObjectName(_fromUtf8("spbRadiusKm"))
        self.gridLayout.addWidget(self.spbRadiusKm, 6, 7, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(66, 27))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 8, 1, 1)
        self.spbRadiusDg = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spbRadiusDg.setDecimals(3)
        self.spbRadiusDg.setMinimum(1.0)
        self.spbRadiusDg.setMaximum(5000.0)
        self.spbRadiusDg.setProperty("value", 5.0)
        self.spbRadiusDg.setObjectName(_fromUtf8("spbRadiusDg"))
        self.gridLayout.addWidget(self.spbRadiusDg, 6, 9, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(66, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 5, 6, 1, 4)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(66, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 7, 1, 2)
        self.spbRadius = QtGui.QSpinBox(self.layoutWidget)
        self.spbRadius.setMinimum(6000000)
        self.spbRadius.setMaximum(7000000)
        self.spbRadius.setSingleStep(0)
        self.spbRadius.setProperty("value", 6371000)
        self.spbRadius.setObjectName(_fromUtf8("spbRadius"))
        self.gridLayout.addWidget(self.spbRadius, 1, 9, 1, 1)
        self.lblCircleSeg = QtGui.QLabel(self.layoutWidget)
        self.lblCircleSeg.setMinimumSize(QtCore.QSize(144, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCircleSeg.setFont(font)
        self.lblCircleSeg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCircleSeg.setObjectName(_fromUtf8("lblCircleSeg"))
        self.gridLayout.addWidget(self.lblCircleSeg, 0, 7, 1, 2)
        self.chkBoxSPole = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkBoxSPole.setFont(font)
        self.chkBoxSPole.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBoxSPole.setObjectName(_fromUtf8("chkBoxSPole"))
        self.gridLayout.addWidget(self.chkBoxSPole, 4, 8, 1, 2)
        self.spbCircleSeg = QtGui.QSpinBox(self.layoutWidget)
        self.spbCircleSeg.setMinimum(5)
        self.spbCircleSeg.setMaximum(100)
        self.spbCircleSeg.setProperty("value", 50)
        self.spbCircleSeg.setObjectName(_fromUtf8("spbCircleSeg"))
        self.gridLayout.addWidget(self.spbCircleSeg, 0, 9, 1, 1)
        self.chkBoxNPole = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkBoxNPole.setFont(font)
        self.chkBoxNPole.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkBoxNPole.setObjectName(_fromUtf8("chkBoxNPole"))
        self.gridLayout.addWidget(self.chkBoxNPole, 3, 8, 1, 2)

        self.retranslateUi(Tiss)
        QtCore.QMetaObject.connectSlotsByName(Tiss)

    def retranslateUi(self, Tiss):
        Tiss.setWindowTitle(_translate("Tiss", "Tiss", None))
        self.btnRun.setText(_translate("Tiss", "Run!", None))
        self.lblLongMax.setText(_translate("Tiss", "Lon. max", None))
        self.lblLongMin.setText(_translate("Tiss", "Lon. min", None))
        self.lblLatMax.setText(_translate("Tiss", "Lat. max", None))
        self.lblLatMin.setText(_translate("Tiss", "Lat. min", None))
        self.label_10.setText(_translate("Tiss", "Extent", None))
        self.lblRadius.setText(_translate("Tiss", "Latitude resolution: ", None))
        self.label_6.setText(_translate("Tiss", "Longitude resolution:", None))
        self.lblCircleSeg_2.setText(_translate("Tiss", "Line segments", None))
        self.label_11.setText(_translate("Tiss", "[km]: ", None))
        self.label_9.setText(_translate("Tiss", "[degree]: ", None))
        self.label_8.setText(_translate("Tiss", "Radius of the circles", None))
        self.label_12.setText(_translate("Tiss", "Spherical radius [m]", None))
        self.lblCircleSeg.setText(_translate("Tiss", "Circle segments", None))
        self.chkBoxSPole.setText(_translate("Tiss", "Circle on south pole", None))
        self.chkBoxNPole.setText(_translate("Tiss", "Circle on north pole", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Tiss = QtGui.QDialog()
    ui = Ui_Tiss()
    ui.setupUi(Tiss)
    Tiss.show()
    sys.exit(app.exec_())

